# trajectory Optimizer
mini_T:                   0.05
wei_time_:                100.0
#wheelbase = 0.5
kmax:                     2.0 #2.0+0.1 1.5
kdotmax:                  1.0
cons_eps_:                0.1


vmax:                     2.0
latAccmax:                1.5
lonAccmax:                1.5
accRatemax:               1.5
phimax: 0.785
omegamax: 0.4 #0.5-0.02


traj_res:                 16
past:                     0
rho:                      1.0
rho_max:                  1000.0
gamma:                    1.0
mem_size:                 256
g_epsilon:                1.0
min_step:                 1.0e-32
delta:                    1.0e-1
max_iterations:           1000
amlMaxIter:               20
useDP:                    false
penaWei:                  5000.0
esdfWei:                  10000.0

pieceTime:                1.2
miniS:                    0.1
safeMargin:               0.1 #0.15+0.05
conpts:                   [[0.0, 0.0], [0.2, -0.00]]
non_siguav:               1.0





#map
mapRes:                   0.1
mapX:                     20.0
mapY:                     20.0
expandSize:               0 
wheel_base:               0.6
horizon_:                 50.0

yaw_resolution_:          3.15
lambda_heu_:              1.0


#0:48134 1:21376 2:19494 3:5794 4:4041 5:3064
allocate_num_:            1000000
check_num_:               8
step_arc:                 0.3
checkl:                   0.15

max_seach_time:           20.0
backW:                    1.0

isdebug:                  false
isfixGear:                true
isVis:                    false
enable_shot:              false